// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBOxI0e9Dq40l4KvseVU5UzJqriwy3Juh0',
    appId: '1:1080395044689:web:da44f968a0ceec57a7a570',
    messagingSenderId: '1080395044689',
    projectId: 'vexa-9a86f',
    authDomain: 'vexa-9a86f.firebaseapp.com',
    storageBucket: 'vexa-9a86f.firebasestorage.app',
    measurementId: 'G-FBF50RB1G9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB4OkuurQPQJL9yCgCjH2F4BQEkm3Ee5PI',
    appId: '1:1080395044689:android:08e6c1b0f6ee59e4a7a570',
    messagingSenderId: '1080395044689',
    projectId: 'vexa-9a86f',
    storageBucket: 'vexa-9a86f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDwxBkJFQh6XcOlllq_8NqZG91ODSfRB_Y',
    appId: '1:1080395044689:ios:2a88495730df7654a7a570',
    messagingSenderId: '1080395044689',
    projectId: 'vexa-9a86f',
    storageBucket: 'vexa-9a86f.firebasestorage.app',
    iosBundleId: 'com.example.mobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDwxBkJFQh6XcOlllq_8NqZG91ODSfRB_Y',
    appId: '1:1080395044689:ios:2a88495730df7654a7a570',
    messagingSenderId: '1080395044689',
    projectId: 'vexa-9a86f',
    storageBucket: 'vexa-9a86f.firebasestorage.app',
    iosBundleId: 'com.example.mobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBOxI0e9Dq40l4KvseVU5UzJqriwy3Juh0',
    appId: '1:1080395044689:web:5df54f78076f4660a7a570',
    messagingSenderId: '1080395044689',
    projectId: 'vexa-9a86f',
    authDomain: 'vexa-9a86f.firebaseapp.com',
    storageBucket: 'vexa-9a86f.firebasestorage.app',
    measurementId: 'G-YBL8DV3291',
  );
}
